### ISSUE TITLE
About import the module "pydarknet" 

### ISSUE THREAD

**Issue by dailinsubjam** [xiaoyuuuuu/dac-hdc-2018-object-detection-in-Jetson-TX2#1]
I encountered the error message "ModuleNotFoundError: No module named 'pydarknet' " when running main_ex.py... Do I have to do something else (such as making some modules in C program available to the python program) before compiling main_ex.py ?

**Comment by srzhu97** [comment]
I met the same problem as you. You should first successfully "make"  and then you can see a pydarknet.so module in the file. Put the pydarknet.so in the file where you want to execute main_ex.py.

**Comment by dailinsubjam** [comment]
@srzhu97 Thank you very much.

**Comment by scutzhe** [comment]
> @srzhu97 Thank you very much.
pydarknet.so: undefined symbol: cudnnConvolutionForward
